services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: next-nest-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - WATCHPACK_POLLING=true
    tty: true

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: next-nest-app
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    # command: npm run start:dev -- --preserveWatchOutput
    tty: true