services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: next-nest-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - WATCHPACK_POLLING=true
    tty: true

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: next-nest-app
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    # command: npm run start:dev -- --preserveWatchOutput
    tty: true
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: next-nest-db
    env_file:
      - .env
    ports:
      -"5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: